### ISSUE TITLE
Heroku 16

### ISSUE THREAD

**Issue by bkovacev** [heroku/heroku-buildpack-xvfb-google-chrome#12]
When will you support `Heroku 16` stack?

**Comment by JeffMv** [comment]
Hi,
any update for heroku-16 ? Or maybe even the heroku-18 stack ?

**Comment by jgladch** [comment]
Bump

**Comment by joshwlewis** [comment]
Sorry, we're unlikely to support the xvfb version of this buildpack in any of the `heroku-*` stacks. The `heroku-*` stacks are missing quite a few xvfb dependencies that were available in the `cedar-14` stack. Building those dependencies in a buildpack requires some nasty patching of binaries, that didn't feel safe or secure.

Instead, I'd suggest considering the [non-xvfb buildpack](https://github.com/heroku/heroku-buildpack-google-chrome). Or, depending on your usage, you might be able to leverage docker deploys to build your own heroku-16 image with xvfb and chrome: https://devcenter.heroku.com/articles/container-registry-and-runtime.

**Comment by swrobel** [comment]
"While headless Chrome is stable, some use cases (like filling in fields via Selenium) require an X window server to be active. For those cases, please see the heroku-xvfb-google-chrome buildpack instead."

Seems like a pretty massive drawback to me that will prevent my apps (and I'd imagine many others) from using Heroku CI.

**Comment by jdnixx** [comment]
So........what about now that Cedar-14 is supposedly deprecated?

Does this still not work in Heroku-18? If not, then is there just no way to get the xvfb buildpack currently?

**Comment by joshwlewis** [comment]
> So........what about now that Cedar-14 is supposedly deprecated?

Once the Cedar-14 stack becomes unavailable, this buildpack will not work on the Heroku platform. 

> While headless Chrome is stable, some use cases (like filling in fields via Selenium) require an X window server to be active. For those cases, please see the heroku-xvfb-google-chrome buildpack instead.

In our testing, this is no longer true (and we've removed that line from our documentation). Selenium and headless chrome work well together now, and most (if not all) testing needs can be covered without XVFB.

**Comment by jdnixx** [comment]
> > While headless Chrome is stable, some use cases (like filling in fields via Selenium) require an X window server to be active. For those cases, please see the heroku-xvfb-google-chrome buildpack instead.
> 
> In our testing, this is no longer true (and we've removed that line from our documentation). Selenium and headless chrome work well together now, and most (if not all) testing needs can be covered without XVFB.

Ah yeah I just found this out last night while testing, good to know.

**Comment by swrobel** [comment]
> In our testing, this is no longer true (and we've removed that line from our documentation).

It's still present on https://github.com/heroku/heroku-buildpack-google-chrome

**Comment by edmorley** [comment]
> It's still present on https://github.com/heroku/heroku-buildpack-google-chrome

Hi! Ah yes good spot - I've fixed the docs in:
https://github.com/heroku/heroku-buildpack-google-chrome/pull/71
